/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;


import Dao.ProdutoDAO;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import modelo.Produto;
import factory.ConnectionFactory;


/**
 *
 * @author cauaq
 */
public class TelaGerenciarProduto extends javax.swing.JFrame {

    /**
     * Creates new form TelaGerenciarProduto
     */
    public TelaGerenciarProduto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nomeProdutoField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        quantidadeLabel = new javax.swing.JLabel();
        procedenciaLabel = new javax.swing.JLabel();
        descricaoLabel = new javax.swing.JLabel();
        nomeLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnApagarProduto = new javax.swing.JButton();
        btnEditarProduto = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(148, 161, 178));

        jPanel2.setBackground(new java.awt.Color(70, 12, 169));

        jLabel1.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Produtos");

        jButton1.setBackground(new java.awt.Color(148, 161, 178));
        jButton1.setFont(new java.awt.Font("Sitka Small", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(70, 12, 169));
        jButton1.setText("Add produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 12, 169));
        jLabel2.setText("nome do produto:");

        nomeLabel.setBackground(new java.awt.Color(70, 12, 169));

        jLabel3.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");

        jLabel4.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descrição:");

        jLabel5.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Procedência:");

        jLabel6.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantidade em estoque:");

        quantidadeLabel.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        quantidadeLabel.setForeground(new java.awt.Color(255, 255, 255));
        quantidadeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeLabel.setText("Saída");

        procedenciaLabel.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        procedenciaLabel.setForeground(new java.awt.Color(255, 255, 255));
        procedenciaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procedenciaLabel.setText("Saída");

        descricaoLabel.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        descricaoLabel.setForeground(new java.awt.Color(255, 255, 255));
        descricaoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descricaoLabel.setText("Saída");

        nomeLabel1.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        nomeLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nomeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomeLabel1.setText("Saída");

        javax.swing.GroupLayout nomeLabelLayout = new javax.swing.GroupLayout(nomeLabel);
        nomeLabel.setLayout(nomeLabelLayout);
        nomeLabelLayout.setHorizontalGroup(
            nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomeLabelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(procedenciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nomeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(descricaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        nomeLabelLayout.setVerticalGroup(
            nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomeLabelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeLabel1))
                .addGap(64, 64, 64)
                .addGroup(nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(descricaoLabel))
                .addGap(66, 66, 66)
                .addGroup(nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(procedenciaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(nomeLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(quantidadeLabel))
                .addGap(51, 51, 51))
        );

        btnBuscar.setBackground(new java.awt.Color(148, 161, 178));
        btnBuscar.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(70, 12, 169));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setBorderPainted(false);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnApagarProduto.setBackground(new java.awt.Color(148, 161, 178));
        btnApagarProduto.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnApagarProduto.setForeground(new java.awt.Color(70, 12, 169));
        btnApagarProduto.setText("Apagar produto");
        btnApagarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnApagarProduto.setBorderPainted(false);
        btnApagarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarProdutoActionPerformed(evt);
            }
        });

        btnEditarProduto.setBackground(new java.awt.Color(148, 161, 178));
        btnEditarProduto.setFont(new java.awt.Font("Sitka Small", 1, 11)); // NOI18N
        btnEditarProduto.setForeground(new java.awt.Color(70, 12, 169));
        btnEditarProduto.setText("Editar produto");
        btnEditarProduto.setBorder(null);
        btnEditarProduto.setBorderPainted(false);
        btnEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProdutoActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnApagarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(btnEditarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(nomeProdutoField)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeProdutoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnApagarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEditarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        TelaCadastroProdutos TelaCadastroProdutos = new TelaCadastroProdutos();
        TelaCadastroProdutos.setVisible(true);  // Abre a tela de cadastro
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nomeProduto = nomeProdutoField.getText();  // Pegando o nome do produto

    if (nomeProduto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, insira o nome do produto.");
        return;
    }

    ProdutoDAO produtoDAO = new ProdutoDAO();
    try {
        Produto produto = produtoDAO.buscarProdutoPorNome(nomeProduto);
        if (produto != null) {
            // Preencher os JLabels com as informações do produto
            nomeLabel1.setText(produto.getNomeProduto());
            descricaoLabel.setText(produto.getDescricao());
            procedenciaLabel.setText(produto.getProcedencia());
            quantidadeLabel.setText("" + produto.getQuantidadeProdutos());
        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar o produto: " + e.getMessage());
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProdutoActionPerformed
          
         String nomeProduto = nomeLabel1.getText().trim(); // pega o nome do produto selecionado

    ProdutoDAO produtoDao = new ProdutoDAO();
    Produto produto = null;

    try {
        produto = produtoDao.buscarProdutoPorNome(nomeProduto);
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Erro ao buscar produto: " + ex.getMessage());
        ex.printStackTrace();
        return;
    }

    if (produto == null) {
        JOptionPane.showMessageDialog(this, "Produto não encontrado!");
        return;
    }

    TelaCadastroProdutos telaCadastro = new TelaCadastroProdutos();
    telaCadastro.preencherFormulario(produto);  // preenche os campos na tela de cadastro
    telaCadastro.setVisible(true);
    this.dispose();

        
    }//GEN-LAST:event_btnEditarProdutoActionPerformed

    private void btnApagarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarProdutoActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza de que deseja excluir este produto?", "Confirmar exclusão", JOptionPane.YES_NO_OPTION);

    if (confirmacao == JOptionPane.YES_OPTION) {
        String nomeProduto = nomeLabel1.getText().replace("Nome: ", "");
        ProdutoDAO produtoDAO = new ProdutoDAO();

        try {
            Produto produto = produtoDAO.buscarProdutoPorNome(nomeProduto);
            if (produto != null) {
                produtoDAO.excluirProduto(produto.getId());  // Excluindo o produto do banco de dados
                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
                
                // Limpa os campos após exclusão
                nomeLabel1.setText("");
                descricaoLabel.setText("");
                procedenciaLabel.setText("");
                quantidadeLabel.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Produto não encontrado.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o produto: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnApagarProdutoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
       TelaInicial telaInicial = new TelaInicial();
    telaInicial.setVisible(true);  // Abre a tela inicial
    this.dispose();  // Fecha a tela atual
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGerenciarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGerenciarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagarProduto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditarProduto;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel nomeLabel;
    private javax.swing.JLabel nomeLabel1;
    private javax.swing.JTextField nomeProdutoField;
    private javax.swing.JLabel procedenciaLabel;
    private javax.swing.JLabel quantidadeLabel;
    // End of variables declaration//GEN-END:variables
}
